spring:
  jackson:
    default-property-inclusion: non_null
  redis:
    port: 3100
    host: 106.12.88.80
    password: 1qaz@WSX
ribbon:
  #请求处理的超时时间
  ReadTimeout: 120000
  #请求连接的超时时间
  ConnectTimeout: 30000
feign:
  hystrix:
    enabled: true