zuul:
  routes:
    weather:
      path: /weather/**
      serviceId: weather-collect-amap-service
    city:
      path: /city/**
      serviceId: weather-city-amap-service
  ratelimit:
    enabled: true
    repository: redis
    policy-list:
      weather:
        - limit: 1
          refresh-interval: 1
          type:
            - origin
      city:
        - limit: 1
          refresh-interval: 1
          type:
            - origin
    