weather:
  heWeather: 
    url: https://free-api.heweather.net/s6/weather/now?
    username: *
    key: *
  senWeather:
    url: https://api.seniverse.com/v3/weather/
    privateKey: *
    publicKey: *
spring:
  jackson:
    default-property-inclusion: non_null
  redis:
    port: 6379
    host: 127.0.0.1