server:
  port: 16000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #指定sentinel控制台地址
        dashboard: 127.0.0.1:8080
    gateway:
     discovery:
       locator:
         #让gateway通过服务发现组件找到其他微服务
         enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always