spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://106.12.88.80:3306/weather?serverTimezone=Asia/Shanghai
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1qaz@WSX
  jackson:
    default-property-inclusion: non_null
ribbon:
  eager-load:
    enabled: true
feign:
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeOut: 15000
logging:
  level: 
    com.istimeless.weathercity.client: debug
weather:
  city:
    url: https://restapi.amap.com/v3/config/district?
    key: 7302cb4144922709c2f4d337a3895476