server:
  port: 17000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #指定sentinel控制台地址
        dashboard: 127.0.0.1:8080
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-wait: -1
        max-idle: 8
        max-active: 8
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weather?serverTimezone=Asia/Shanghai
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1qaz@WSX
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
ribbon:
  eager-load:
    enabled: true
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        loggerLevel: basic
        connectTimeout: 5000
        readTimeOut: 15000
logging:
  level:
    com.istimeless.weathercity.client: debug
  file: ./weather-ip.log
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always